if (NOT TARGET_MCU)
    message(FATAL_ERROR "Error: 请在project-settings.cmake中指定 TARGET_MCU.")
elseif(TARGET_MCU MATCHES "STM32F103VB")
    set(MCU_SERIES "STM32F1xx")
    set(MCU_LINE   "STM32F103xB")
    set(CPU "cortex-m3")
    set(FPU "")
    set(FLOAT_ABI "")
elseif(TARGET_MCU MATCHES "STM32F103C8")
    set(MCU_SERIES "STM32F1xx")
    set(MCU_LINE   "STM32F103xB")
    set(CPU "cortex-m3")
    set(FPU "")
    set(FLOAT_ABI "")
else()
    message(FATAL_ERROR "Error: 未知的TARGET_MCU")
endif()

message(STATUS "TARGET_MCU: ${TARGET_MCU}")
message(STATUS "MCU_SERIES: ${MCU_SERIES}")
message(STATUS "MCU_LINE: ${MCU_LINE}")